name: Django CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    env:
      DEBUG: 0
      SECRET_KEY: test-secret-key
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_HOST: localhost
      DB_PORT: 5432

    steps:
      - name: 🔄 Checkout do repositório
        uses: actions/checkout@v3

      - name: 🐍 Instala o Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: 📦 Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🛠️ Roda as migrações
        run: python manage.py migrate

      - name: ✅ Roda os testes
        run: python manage.py test

      # (Opcional) - Adicione o deploy se quiser
      # - name: 🚀 Deploy (exemplo fictício)
      #   run: ssh user@seu-server.com 'cd /caminho/projeto && git pull && docker-compose up -d --build'
